Controllers/HopDongController.cs
using Microsoft.AspNetCore.Mvc;
using QLNS.Data.Interface;
using QLNS.Model;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Dapper;

namespace QLNS.Controllers
{
    [Route("api/[controller]")]
    public class HopDongController : Controller
    {
        private IHopDongRepository hopDongRepository;

        public HopDongController(IHopDongRepository hopDongRepository)
        {
            this.hopDongRepository = hopDongRepository;
        }

        // GET: HopDong
        public async Task<IActionResult> Index()
        {
            return View(await hopDongRepository.getAll());
        }

        // GET: 
        [Route("Details")]
        [HttpGet("{id}")]
        public async Task<IActionResult> Get(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            return View(await hopDongRepository.getById(id));
        }

        [Route("Create")]
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [Route("Create")]
        [HttpPost]
        public async Task<IActionResult> Create([FromForm]Hopdong hopdong)
        {
            if (ModelState.IsValid)
            {
                await this.hopDongRepository.Create(hopdong);
                return RedirectToAction("Index");
            }
            else
                return Content("Hi there!");
           

        }

        [Route("Update")]
        [HttpGet("{id}")]
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            return View(await hopDongRepository.getById(id));
        }
        [Route("Update")]
        [HttpPost]
        //public int ID = 
        public async Task<IActionResult> Update([FromForm]Hopdong hopdong)
        {
          
           
            if (ModelState.IsValid)
            {
                
                    await this.hopDongRepository.Update(hopdong);
                    return RedirectToAction("Index");
                
                
            }

            else
                return Content("Hi there!");

        }

        [Route("Delete")]
        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await this.hopDongRepository.Delete(id);

            return RedirectToAction("Index");

        }
    }
}

Views/HopDong/Create.cshtml
@model QLNS.Model.Hopdong

<h4>Hopdong</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form id="frmHopDong" asp-action="Create" asp-controller="HopDong" method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Sohopdong" class="control-label"></label>
                <input asp-for="Sohopdong" name="Sohopdong" class="form-control" />
                <span asp-validation-for="Sohopdong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ten" class="control-label"></label>
                <input asp-for="Ten" name="Ten" class="form-control" />
                <span asp-validation-for="Ten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Noidung" class="control-label"></label>
                <input asp-for="Noidung" name="Noidung" class="form-control" />
                <span asp-validation-for="Noidung" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                    <label asp-for="Ngaylap" class="control-label"></label>
                    <input asp-for="Ngaylap" class="form-control" />
                    <span asp-validation-for="Ngaylap" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Useradd" class="control-label"></label>
                    <input asp-for="Useradd" class="form-control" />
                    <span asp-validation-for="Useradd" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Dateedit" class="control-label"></label>
                    <input asp-for="Dateedit" class="form-control" />
                    <span asp-validation-for="Dateedit" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Useredit" class="control-label"></label>
                    <input asp-for="Useredit" class="form-control" />
                    <span asp-validation-for="Useredit" class="text-danger"></span>
                </div>*@
            <div class="form-group">
                <button id="Submit" onclick="Submit()" class="btn btn-default" >Submit </button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.js"
        integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>

<script type="text/javascript">
    function Submit() {
        alert("call");
            $.ajax({
                    url: '@Url.Action("", "HopDong")',
                data: $('#frmHopDong').serialize(),
                type: 'POST',
                    success: function (result) {
                        alert(result);
                    }
                });

    }
    </script>

Views/HopDong/Delete.cshtml
@model QLNS.Model.Hopdong

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Hopdong</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Sohopdong)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Sohopdong)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Ten)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ten)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Noidung)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Noidung)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Ngaylap)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ngaylap)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Dateadd)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Dateadd)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Useradd)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Useradd)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Dateedit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Dateedit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Useredit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Useredit)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" value="" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/HopDong/Get.cshtml
@model QLNS.Model.Hopdong

@{
    ViewData["Title"] = "Get";
}

<h2>Get</h2>

<div>
    <h4>Hopdong</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Sohopdong)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Sohopdong)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Ten)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ten)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Noidung)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Noidung)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Ngaylap)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ngaylap)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Dateadd)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Dateadd)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Useradd)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Useradd)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Dateedit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Dateedit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Useredit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Useredit)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { @*id = Model.id*@}) |
    <a asp-action="Index">Back to List</a>
</div>

Views/HopDong/Index.cshtml
@model IEnumerable<QLNS.Model.Hopdong>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>

    @*<a asp-action="Create">Create nè </a>*@
    @Html.ActionLink("Create nè", "Create", "HopDong")
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Sohopdong)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ten)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Noidung)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ngaylap)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Dateadd)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Useradd)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Dateedit)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Useredit)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sohopdong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ten)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Noidung)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ngaylap)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dateadd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Useradd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dateedit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Useredit)
            </td>
            <td>
               
             
                @Html.ActionLink("Edit", "Update", new { id = item.Id }) |
                @Html.ActionLink("Details", "Get", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

Views/HopDong/Update.cshtml
@model QLNS.Model.Hopdong

<h4>Hopdong</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update" asp-controller="HopDong" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           @*<input type="text" asp-for="Id" value="@Model.Id" asp-route-id="@Model.Id" />*@
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" name="Id" value="@Model.Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sohopdong" class="control-label"></label>
                <input asp-for="Sohopdong" name="Sohopdong" class="form-control" />
                <span asp-validation-for="Sohopdong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ten" class="control-label"></label>
                <input asp-for="Ten" name="Ten" class="form-control" />
                <span asp-validation-for="Ten" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Noidung" class="control-label"></label>
                <input asp-for="Noidung" name="Noidung" class="form-control" />
                <span asp-validation-for="Noidung" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ngaylap" class="control-label"></label>
                <input asp-for="Ngaylap" name="Ngaylap" class="form-control" />
                <span asp-validation-for="Ngaylap" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dateadd" class="control-label"></label>
                <input asp-for="Dateadd" class="form-control" />
                <span asp-validation-for="Dateadd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Useradd" class="control-label"></label>
                <input asp-for="Useradd" class="form-control" />
                <span asp-validation-for="Useradd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Dateedit" class="control-label"></label>
                <input asp-for="Dateedit" class="form-control" />
                <span asp-validation-for="Dateedit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Useredit" class="control-label"></label>
                <input asp-for="Useredit" class="form-control" />
                <span asp-validation-for="Useredit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" asp-route-id value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}